language: php
compiler:
  - gcc
addons:
  apt:
    packages:
      - valgrind
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  global:
    - REPORT_EXIT_STATUS=1
  matrix:
    - TEST_PHP_ARGS="-q --show-diff -d opcache.enable_cli=0"
    - TEST_PHP_ARGS="-q --show-diff -d opcache.enable_cli=1 -d opcache.optimization_level=0x7FFEBFFF"

before_install:
  - pip install --user cpp-coveralls

before_script:
  - echo "variables_order=EGPCS" >> $HOME/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/php.ini
  - echo                          > $HOME/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/xdebug.ini
  - echo "extension=componere.so" > $HOME/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/componere.ini

script:
  - phpize
  - wget -q -O run-tests.php https://raw.githubusercontent.com/php/php-src/master/run-tests.php
  - ./configure --enable-componere-coverage
  - make componere-test-coverage
  - make install
  - php run-tests.php -P tests

after_success:
  - coveralls -b $TRAVIS_BUILD_DIR -E Zend --gcov-options '\-lp'
