language: php
addons:
  apt:
    packages:
      - valgrind
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  global:
    - REPORT_EXIT_STATUS=1
  matrix:
    - TEST_PHP_ARGS="-m -q --show-diff"
    - TEST_PHP_ARGS="-q --show-diff"

script:
  - phpize
  - ./configure
  - make
  - make test
