language: php
compiler:
  - gcc
addons:
  apt:
    packages:
      - valgrind
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  global:
    - REPORT_EXIT_STATUS=1
  matrix:
    - TEST_PHP_ARGS="-m -q --show-diff --show-mem"
    - TEST_PHP_ARGS="-q --show-diff"
    - TEST_PHP_ARGS="-m -q --show-diff --show-mem -dopcache.enable_cli=1 -dopcache.optimization_level=0x7FFEBFFF"
    - TEST_PHP_ARGS="-q --show-diff -dopcache.enable_cli=1 -dopcache.optimization_level=0x7FFEBFFF"

matrix:
  allow_failures:
    - php: nightly
      env: TEST_PHP_ARGS="-m -q --show-diff --show-mem"
      env: TEST_PHP_ARGS="-m -q --show-diff --show-mem -dopcache.enable_cli=1 -dopcache.optimization_level=0x7FFEBFFF"

before_install:
  - pip install --user cpp-coveralls

script:
  - phpize
  - wget -q -O run-tests.php https://raw.githubusercontent.com/php/php-src/master/run-tests.php
  - ./configure --enable-componere-coverage
  - make
  - make componere-test-coverage

after_success:
  - coveralls -b $TRAVIS_BUILD_DIR -E Zend --gcov-options '\-lp'
